---
- name: Get defaults
  include_vars:
    file: "{{ playbook_dir }}/config/defaults.yml"
    namespace: service-mesh
    state: present
    src: "{{ playbook_dir }}/config/gateway.yaml"


- name:  Create Kind Cluster
  command: 'kind create cluster --name test --config  "{{ playbook_dir }}/config/kind-config.yaml" '
  register: sh_info

- name:   Get Kind Cluster
  command: 'kind get clusters '
  register: sh_info


